name: Zabi Zarodek
favicon: null
layout_spectrum: 0.2649358280468732
typography_spectrum: 0.6105338395573199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9a097'
    - '#004181'
    - '#71726c'
    - '#0c1514'
    - '#f5f4f2'
  brandStrength: 0.875
  lightness: 0.12541332165710628
  saturation: 0.38112018536776304
  rhythmicContrast: 0.25
purpose: []
